name: cime

on: [push,pull_request]


jobs:
    cime:
        runs-on: ubuntu-latest
        steps:
            - name: depandinces
              run: |
                pip install -r ../../requirements.txt
                pip install pytest
            - name: run py
              run: python pytest    